version: '3'
services:
  routinator:
    image: 'lspgn/routinator'
    command: -r -l 0.0.0.0:3323 -v -c /cache -o /output/output.json
    ports:
      - '3323:3323'
    volumes:
      - ./tals:/root/.rpki-cache/tals/
      - ./cache:/cache/
      - ./output:/output/